# Author information
author: Javier Diaz Chamorro
position: Senior Frontend Developer
workat: Cultura Colectiva

# Seo
title: Javier Diaz
slogan: Fullstack JavaScript Developer based on Mexico City
description: Online Portfolio of Fullstack JavaScript Developer, Javier Diaz.
image: ""

# Jekyll configuration
baseurl: ""
url: "https://coderdiaz.me"
permalink: /:year/:month/:day/:title/
markdown: kramdown
exclude: [
  Gemfile,
  Gemfile.lock,
  scss,
  node_modules,
  package-lock.json,
  src,
  package.json,
  yarn.lock,
  CNAME,
  README.md
]

# Alias to directories
assets:
  css: assets/css/
  svg: assets/svg/
  img: assets/img/
  js: assets/js/

# SASS configuration
sass:
  sass_dir: assets/_scss
  style: :compressed