# Author information
author: Javier Diaz
position: Fullstack JavaScript Engineer & teacher
work:
  at: BEDU
  url: https://bedu.org
livesin: Mexico City 
editor:
  name: Visual Studio Code
  url: https://code.visualstudio.com/
yearsxp: 5 years
username: coderdiaz

# Dribbble
dribbble:
  token: c45be162c0dae8c4c3ea96a4ee734d910149c29b3f3c16abe8ed3595dc118e54

# Seo
title: Javier Diaz
slogan: Fullstack JavaScript Engineer & teacher based on Mexico City
description: Online Portfolio and Blog of Fullstack JavaScript Engineer & teacher, Javier Diaz. Check my work and learn about tech in my personal blog.
image: ""

# Jekyll configuration
baseurl: ""
url: "https://coderdiaz.me"
permalink: /:year/:month/:day/:title/
markdown: kramdown
exclude: [
  Gemfile,
  Gemfile.lock,
  scss,
  node_modules,
  package-lock.json,
  src,
  package.json,
  yarn.lock,
  yarn-error.log,
  assets/js/demo.html,
  assets/img,
  CNAME,
  README.md
]

# Social Networks
social:
  youtube: https://www.youtube.com/channel/UCIZS4F2zlOd1rnx6g7Jye1w
  twitter: https://twitter.com/coderdiaz
  github: https://github.com/coderdiaz
  dribbble: https://dribbble.com/coderdiaz
  vsco: https://vsco.co/coderdiaz

# Alias to directories
assets:
  css: assets/css/
  svg: assets/svg/
  img: assets/img/
  js: assets/js/
  images: assets/images/

# SASS configuration
sass:
  sass_dir: assets/_scss
  style: :compressed